data_ingestion:
  seed: 42
  test_size: 0.2

feature_engineering:
  bow_max_features: 50

model_training:
  estimator:
    criterion: "gini"
    splitter: "best"
    max_depth: 5
    min_samples_split: 5
    min_samples_leaf: 2
    estimator_max_features: 0.85
    estimator_random_state: 40
  
  bagging:
    n_estimators: 500
    max_samples: 0.75
    bagging_max_features: 0.75
    bootstrap: False
    bootstrap_features: False 
    oob_score: False
    warm_start: False
    bagging_random_state: 40
    verbose: 1